Repository gatsbyg/gg, pull requests merged in 2020-05, with the labels that each got.

#13 Hall of Fame
  hall-of-fame.md
  images/logos/gatsby-artists.jpg
  images/logos/gatsby-doom.png
  images/logos/gatsby-maintainers.jpg
Labels: documentation, enhancement

#14 Create getting-started.md
  getting-started.md
Labels: documentation, enhancement

#16 Add 2 more logos
  hall-of-fame.md
  images/logos/team-gopher.png
  images/logos/team-js-advance.jpg
Labels: documentation, enhancement

#17 Update getting-started.md
  getting-started.md
Labels: documentation

#18 Update contributors.md
  contributors.md
Labels: documentation

#19 Add logo
  hall-of-fame.md
  images/logos/beautiful-springtime-gatsby.jpg
Labels: enhancement
